# Generated by Django 5.1.3 on 2024-11-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatures',
            name='humidity1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='humidity2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='humidity3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='humidity4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='humidity5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='temperature1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='temperature2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='temperature3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='temperature4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='temperature5',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
