# Generated by Django 5.1.3 on 2024-11-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempApp', '0005_alter_temperatures_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatures',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
