# Generated by Django 5.1.3 on 2024-11-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempApp', '0009_temperatures_time_alter_temperatures_humidity1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperatures',
            name='time',
        ),
    ]
